### ISSUE TITLE
Vercel Deployment

### ISSUE THREAD

**Issue by saliksik** [CERTIFIED2003/question-answering-ai#1]
Hi Sir Shubham!

Your web app was just recommended to me by Github.

I am starting learning React, Vite, and NextJS. Can you help me or show me how to setup this on Vercel hosting?

Thank you.

**Comment by CERTIFIED2003** [comment]
Sure. 
Firstly I am just a teen student like you :)

You need to understand that this project is not just the frontend part, it has both frontend and backend.
So only hosting it on Vercel will not do. You have to upload your backend on the server too.

There are many free backend hosting but I prefer you should use [Cyclic.sh](https://cyclic.sh)
For frontend I use [Cloudflate](https://cloudflare.com). 

### BACKEND PART
**Step 1)** U can fork this repo or u can just download the code and upload this project on your GitHub repo.
**Step 2)** Head over to [Cyclic.sh](https://cyclic.sh) where we will deploy our backend. After registering or signing in, you will be redirected to their dashboard. 
**Step 3)** From there click on [Deploy](https://app.cyclic.sh/#/deploy) button. Then click on Link Your Own. Search that repo which you have uploaded. Then click on Connect Button.
**Step 4)** After the building process is completed copy the **_App Url_** provided in **_Overview_** Tab. Then head over to **_Variables_** on this project's dashboard. There you have to provide your _**OPENAI_API_KEY**_.

### OPENAI_API_KEY 
**Step 5)** Head over to [OpenAI's](https://openai.com/) website. Then click on **_API_** on the Navbar of the website. Then Click on [Sign Up](https://beta.openai.com/signup) button. After creating your account click on the **_Personal_** tab at top right corner. 
**Step 6)** Then click _**View API Keys**_. Then _**Create new secret key**_. After you have created your api key note it somewhere because you can't be able to see it after then.
**Step 7)** Paste this key to the _**OPENAI_API_KEY**_ in the **_Variables_** on the Cyclic dashboard. **YOUR BACKEND PART IS COMPLETED NOW**

### FRONTEND PART
**Step 8)** As u said u wanted to deploy it on Vercel, head over to Vercel's website and Import the project there.
**Step 9)** Set **_Framework preset_** to **_Vite_**. Set **_Root Directory_** to _**frontend**_. 
**Step 10)** Add Environment variable **_VITE_BACKEND_URL_** to the **_Name_** input field. The **_App Url_** provided in **_Overview_** Tab on **Cyclic.sh** is the **_VITE_BACKEND_URL_**. After then click on **_Deploy_** button.

###  After the build finishes click on Continue to Dashboard and u can view the Deployment

**Also when you try it for first time and ask the question u can find that it shows error in console. This is beacuse it can't communicate with backend url. U can fix it by editing anything on the repo file and commit the changes again. After the second build the project will run smoothly.**

Ask me question again if u face any difficulty.

**Comment by CERTIFIED2003** [comment]
**Leave the Framework field empty.**

### ** Follow from the below ss **
![Screenshot (213)](https://user-images.githubusercontent.com/111045472/214113030-c52aa26a-7a51-4c7d-8d88-bc83511ad17a.png)

**Comment by saliksik** [comment]
I managed to make it work. Thank you so much! I am also a student. I have learn so much from you. One thing I noticed is the formatting of the generated text. But overall, its great! Thanks again.

![Web capture_24-1-2023_21330_frontend-bay-five vercel app](https://user-images.githubusercontent.com/122975898/214117458-33cd0da9-bb84-4d0e-accc-7ca6811e5aee.jpeg)

**Comment by CERTIFIED2003** [comment]
Thanks for such a heart warming reply.
I think i know what's the problem of that text.
Open your Backend **_index.js_** file and remove if there is any code related to **[".", ""]**.
You can compare your code with my my updated [index.js](https://github.com/CERTIFIED2003/question-answering-ai/blob/main/index.js) file.
